.lint-job-default-config:
  stage: meta
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

codespell:
  extends: .lint-job-default-config
  before_script:
    - PATH=$PATH:/home/gitlab-runner/.local/bin # Codespell is installed by pip
  script:
    - codespell -s ./*.md hdl/ host/ scripts/ target/*/{hdl,scripts,host,*.md} tb/ test/
  artifacts:
  tags: [pkgubuntu2204]

autopep8:
  extends: .lint-job-default-config
  script:
    - find host/ target/*/host/ scripts/ test/ -iname "*.py" -print0 | xargs -0 autopep8 --exit-code --diff
  artifacts:
  tags: [pkgubuntu2204]

verible-verilog-format:
  extends: .lint-job-default-config
  script:
    - find hdl/ tb/ target/*/hdl/ -iname "*.sv" -print0 | xargs -0 -n1 verible-verilog-format --verify --flagfile .verible-verilog-format.conf --inplace
  artifacts:
  tags: [vivado]
